{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Python Blackjack\n",
    "For this project you will make a Blackjack game using Python. Click <a href=\"\">here</a> to familiarize yourself with the the rules of the game. You won't be implementing every rule \"down to the letter\" with the game, but we will doing a simpler version of the game. This assignment will be given to further test your knowledge on object-oriented programming concepts.\n",
    "\n",
    "### Rules:\n",
    "\n",
    "`1. ` The game will have two players: the Dealer and the Player. The game will start off with a deck of 52 cards. The 52 cards will consist of 4 different suits: Clubs, Diamonds, Hearts and Spades. For each suit, there will be cards numbered 1 through 13. <br>\n",
    "**Note: No wildcards will be used in the program.**<br>\n",
    "**Note: For the sake of simplicity, You do not have to write any logic to figure out how to handle face cards. Simply give the cards values between 1-13.**\n",
    "\n",
    "`2. ` When the game begins, the dealer will shuffle the deck of cards, making them randomized. After the dealer shuffles, it will deal the player 2 cards and will deal itself 2 cards from. The Player should be able to see both of their own cards, but should only be able to see one of the Dealer's cards.\n",
    " \n",
    "`3. ` The objective of the game is for the Player to count their cards after they're dealt. If they're not satisfied with the number, they have the ability to 'Hit'. A hit allows the dealer to deal the Player one additional card. The Player can hit as many times as they'd like as long as they don't 'Bust'. A bust is when the Player is dealt cards that total more than 21.\n",
    "\n",
    "`4. ` If the dealer deals the Player cards equal to 21 on the **first** deal, the Player wins. This is referred to as Blackjack. Blackjack is **NOT** the same as getting cards that equal up to 21 after the first deal. Blackjack can only be attained on the first deal.\n",
    "\n",
    "`5. ` The Player will never see the Dealer's hand until the Player chooses to 'stand'. A Stand is when the player tells the dealer to not deal it anymore cards. Once the player chooses to Stand, the Player and the Dealer will compare their hands. Whoever has the higher number wins. Keep in mind that the Dealer can also bust. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Your hand:\n",
      "[(6, 'Club'), (10, 'Spade')]\n",
      "Your total: 16\n",
      "\n",
      "Dealer hand:\n",
      "[(11, 'Spade')]\n",
      "Dealer total: 11\n",
      "Would you like to hit or stand? Enter 'h' or 's': s\n",
      "Dealer busted!\n",
      "Dealer busted!\n",
      "Dealer hand:\n",
      "[(11, 'Spade'), (12, 'Heart')]\n",
      "House busts... You win!\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "from IPython.display import clear_output\n",
    "\n",
    "# To do list:\n",
    "# when player stands => dealer hit logic (less than 16 force take hit / more than 17 force stay)\n",
    "# logic for dealer bust human wins\n",
    "# total variable needs to be class specific\n",
    "# if no bust, compare human and dealer score\n",
    "# output who won (dealer/human)\n",
    "# \n",
    "\n",
    "\"\"\"Creates a deck from which cards are output and shuffled\"\"\"\n",
    "class Deck:\n",
    "    \n",
    "    def __init__(self):\n",
    "        self.suits = ['Diamond', 'Heart', 'Club', 'Spade']\n",
    "        self.ranks = range(1,14)\n",
    "        self.cards = [(r, s) for s in self.suits for r in self.ranks]\n",
    "    \n",
    "    def shuffle(self):\n",
    "        print('Dealer is shuffling...')\n",
    "        random.shuffle(self.cards)\n",
    "\n",
    "        \n",
    "\"\"\"Shared attributes/methods for human AND dealer players\"\"\"\n",
    "class Player:\n",
    "    def __init__(self):\n",
    "        self.hand = []\n",
    "        \n",
    "    @classmethod    \n",
    "    def get_total(self, cls):\n",
    "        total = sum([card[0] for card in cls.hand])\n",
    "        if total > 21:\n",
    "            print(cls.bust())\n",
    "        return total\n",
    "    \n",
    "    def bust(self):\n",
    "        return f'{self.__class__.__name__} busted!'\n",
    "\n",
    "    \n",
    "\"\"\"Specific to the person playing the game\"\"\"\n",
    "class Human(Player):\n",
    "    pass\n",
    "\n",
    "\n",
    "\"\"\"Specific to computer dealer\"\"\"\n",
    "class Dealer(Player):\n",
    "    \n",
    "    def deal(self, a_deck, p):\n",
    "        if isinstance(p, Human):\n",
    "       \n",
    "            if len(p.hand) >= 2:\n",
    "                p.hand.append(a_deck.cards.pop())\n",
    "            else:\n",
    "                for i in range(2):\n",
    "                    p.hand.append(a_deck.cards.pop())\n",
    "        elif isinstance(p, Dealer):\n",
    "            p.hand.append(a_deck.cards.pop())\n",
    "        \n",
    "        \n",
    "\"\"\"Game logic - specifies order of operations\"\"\"\n",
    "class Game:\n",
    "    @classmethod\n",
    "    def run(self):\n",
    "        print(\"Welcome to my casino! Let's play Blackjack!\")\n",
    "#        deck = Deck()\n",
    "#        dealer = Dealer()\n",
    "#        human = Human()\n",
    "        \n",
    "#        deck.shuffle()\n",
    "        \n",
    "#       dealer.deal(deck, human)\n",
    "        \n",
    "#       dealer.deal(deck, dealer)\n",
    "\n",
    "        \n",
    "        quit = False\n",
    "        \n",
    "        while not quit:\n",
    "            confirmation = input(\"Would you like to continue playing? Enter 'y' or 'n': \").lower()\n",
    "            deck = Deck()\n",
    "            dealer = Dealer()\n",
    "            human = Human()\n",
    "        \n",
    "            deck.shuffle()\n",
    "        \n",
    "            dealer.deal(deck, human)\n",
    "        \n",
    "            dealer.deal(deck, dealer)\n",
    "            \n",
    "            if confirmation == 'n':\n",
    "                print('Thanks for playing!')\n",
    "                quit = True\n",
    "            elif confirmation == 'y':\n",
    "                game_over = False\n",
    "                while not game_over:\n",
    "                    clear_output()\n",
    "                    print(\"Your hand:\\n\" + str(human.hand))\n",
    "                    print(f'Your total: {Player.get_total(human)}\\n')\n",
    "                    print(\"Dealer hand:\\n\" + str(dealer.hand))\n",
    "                    print(f'Dealer total: {Player.get_total(dealer)}')\n",
    "                    if Player.get_total(human) > 21:\n",
    "                        print(human.hand)\n",
    "                        print(\"You lose!\")\n",
    "                        break\n",
    "                    choice = input(\"Would you like to hit or stand? Enter 'h' or 's': \").lower()\n",
    "                    if choice =='h':\n",
    "                        dealer.deal(deck, human)\n",
    "                        \n",
    "                    elif choice == 's':\n",
    "                        human_loses = False\n",
    "                        while not human_loses:\n",
    "                            if Player.get_total(dealer) < 16:\n",
    "                                dealer.deal(deck, dealer)\n",
    "                            elif Player.get_total(dealer) > 21: \n",
    "                                print(\"Dealer hand:\\n\" + str(dealer.hand))\n",
    "                                print('House busts... You win!')\n",
    "                                game_over = True\n",
    "                                human_loses = True\n",
    "                                break\n",
    "                            else: #Player.get_total(dealer) <= 21:\n",
    "                                clear_output()\n",
    "                                print(\"Your hand:\\n\" + str(human.hand))\n",
    "                                print(f'Your total: {Player.get_total(human)}\\n')\n",
    "                                print(\"Dealer hand:\\n\" + str(dealer.hand))\n",
    "                                print(f'Dealer total: {Player.get_total(dealer)}')\n",
    "                                if Player.get_total(human) > Player.get_total(dealer):\n",
    "                                    print('Congratulations! You won!!!')\n",
    "                                elif Player.get_total(human) == Player.get_total(dealer):\n",
    "                                    print('You tied the dealer... that means you lost. Sorry.')\n",
    "                                else:\n",
    "                                    print('You lost to the dealer')\n",
    "                                \n",
    "                            \n",
    "                                game_over = True               \n",
    "                                human_loses = True\n",
    "                        \n",
    "\n",
    "Game.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
